# Generated by Django 4.2.30 on 2026-05-14 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицировано')),
                ('specializations', models.TextField(blank=True, help_text='Список специализаций через запятую', verbose_name='Специализации')),
                ('criteria_quality', models.FloatField(default=0, verbose_name='Качество кандидатов')),
                ('criteria_speed', models.FloatField(default=0, verbose_name='Скорость закрытия')),
                ('criteria_price', models.FloatField(default=0, verbose_name='Цена')),
                ('criteria_support', models.FloatField(default=0, verbose_name='Поддержка')),
                ('speed_score', models.FloatField(default=0, verbose_name='Скорость (0–10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Агентство',
                'verbose_name_plural': 'Агентства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agencies.agency', verbose_name='Агентство')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='categories',
            field=models.ManyToManyField(blank=True, to='agencies.category', verbose_name='Категории'),
        ),
    ]
