# Generated by Django 4.2.30 on 2026-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('url', models.CharField(help_text='Например: /spb/ или https://example.com/hr-rating-spb/', max_length=300, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город (перелинковка)',
                'verbose_name_plural': 'Города (перелинковка)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Рейтинг HR агентств Москвы 2026', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(default='Независимый рейтинг кадровых агентств Москвы по качеству подбора и скорости закрытия вакансий.', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, default='HR агентства Москва, кадровые агентства, рейтинг рекрутинг 2026', max_length=500, verbose_name='Meta Keywords')),
                ('h1', models.CharField(default='Лучшие HR&#8209;агентства <em>Москвы</em> — без рекламы и накруток', max_length=300, verbose_name='Заголовок H1')),
                ('hero_subtitle', models.TextField(blank=True, default='Мы оцениваем кадровые агентства по качеству подбора, скорости закрытия вакансий и отзывам реальных работодателей. Без платных позиций.', verbose_name='Подзаголовок (герой)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
