# Generated by Django 4.2.30 on 2026-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_citypage_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='agencies_heading',
            field=models.CharField(default='Агентства Москвы', help_text='Например: «Агентства Москвы» или «Лучшие кадровые агентства»', max_length=200, verbose_name='Заголовок раздела «Агентства …»'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='city_filter',
            field=models.CharField(help_text='Точное значение поля «Город» у агентств — например: Санкт-Петербург', max_length=100, verbose_name='Фильтр по Agency.city'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='h1',
            field=models.CharField(default='Лучшие HR&#8209;агентства — без рекламы и накруток', help_text='Поддерживает HTML-теги, например &lt;em&gt;', max_length=300, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='name',
            field=models.CharField(help_text='Например: Санкт-Петербург', max_length=100, verbose_name='Город (отображаемое)'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='name_genitive',
            field=models.CharField(help_text='Например: Санкт-Петербурга — используется в заголовке «Агентства …»', max_length=100, verbose_name='Город (родительный падеж)'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='slug',
            field=models.SlugField(help_text='Например: spb → страница будет на /spb/', unique=True, verbose_name='Slug (часть URL)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyblock',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Полный тег &lt;svg …&gt;…&lt;/svg&gt;', verbose_name='SVG-иконка'),
        ),
        migrations.AlterField(
            model_name='methodologyblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyblock',
            name='text',
            field=models.TextField(verbose_name='Текст (поддерживает &lt;strong&gt;)'),
        ),
    ]
