# Generated by Django 4.2.30 on 2026-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_sitesettings_agencies_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='citypage',
            name='agencies_heading',
            field=models.CharField(blank=True, help_text='Например: «Агентства Санкт-Петербурга». Если пусто — подставится «Агентства {город}».', max_length=200, verbose_name='Заголовок раздела «Агентства …»'),
        ),
    ]
