# Generated by Django 4.2.30 on 2026-05-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_citypage_agencies_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='city_page',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым — будет глобальным (для всех городов без своих FAQ).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='agencies.citypage', verbose_name='Страница города'),
        ),
        migrations.AddField(
            model_name='methodologyblock',
            name='city_page',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым — будет глобальным (для всех городов без своих блоков).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methodology_blocks', to='agencies.citypage', verbose_name='Страница города'),
        ),
    ]
