# Generated by Django 4.2.30 on 2026-05-18 20:31

from django.db import migrations, models
from django.utils.text import slugify

_TRANSLIT = str.maketrans({
    'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'yo','ж':'zh',
    'з':'z','и':'i','й':'j','к':'k','л':'l','м':'m','н':'n','о':'o',
    'п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'kh','ц':'ts',
    'ч':'ch','ш':'sh','щ':'sch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu',
    'я':'ya',
    'А':'a','Б':'b','В':'v','Г':'g','Д':'d','Е':'e','Ё':'yo','Ж':'zh',
    'З':'z','И':'i','Й':'j','К':'k','Л':'l','М':'m','Н':'n','О':'o',
    'П':'p','Р':'r','С':'s','Т':'t','У':'u','Ф':'f','Х':'kh','Ц':'ts',
    'Ч':'ch','Ш':'sh','Щ':'sch','Ъ':'','Ы':'y','Ь':'','Э':'e','Ю':'yu',
    'Я':'ya',
})


def populate_slugs(apps, schema_editor):
    Agency = apps.get_model('agencies', 'Agency')
    used = set()
    for agency in Agency.objects.all():
        base = slugify(agency.name.translate(_TRANSLIT)) or f"agency-{agency.pk}"
        candidate = base
        i = 1
        while candidate in used:
            candidate = f"{base}-{i}"
            i += 1
        used.add(candidate)
        agency.slug = candidate
        agency.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_faq_methodology_per_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на изображение логотипа', verbose_name='Логотип (URL)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
