# Generated by Django 4.2.30 on 2026-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_add_slug_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('yandex', 'Яндекс.Карты'), ('google', 'Google Maps'), ('2gis', '2ГИС'), ('hh', 'hh.ru'), ('zoon', 'Zoon'), ('other', 'Другой источник')], default='other', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='review',
            name='source_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на оригинальный отзыв', verbose_name='Ссылка на отзыв'),
        ),
    ]
