# Generated by Django 4.2.30 on 2026-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_add_review_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='ext_2gis_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='2ГИС — кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_2gis_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='2ГИС — рейтинг'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_2gis_url',
            field=models.URLField(blank=True, verbose_name='2ГИС — URL карточки'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_google_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Google — кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_google_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Google — рейтинг'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_google_url',
            field=models.URLField(blank=True, verbose_name='Google Maps — URL карточки'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Внешние рейтинги обновлены'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_yandex_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Яндекс — кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_yandex_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Яндекс — рейтинг'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ext_yandex_url',
            field=models.URLField(blank=True, verbose_name='Яндекс.Карты — URL карточки'),
        ),
    ]
