# Generated by Django 4.2.30 on 2026-05-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_add_review_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='map_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (карта)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='map_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (карта)'),
        ),
    ]
